[package]
name        = "apimokka-model"
description = "Workspace, snapshot, edit-command, and trace data types for the apimokka GUI."
readme      = "README.md"
version.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
authors.workspace       = true
repository.workspace    = true

[dependencies]
uuid.workspace              = true
